#!/usr/bin/env bash

wmname LG3D

bspc config border_width         5
bspc config window_gap          21

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config pointer_follows_focus false

bspc config focused_border_color "#B8BB26"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
