#!/bin/sh

# Where the repo has been cloned to
dotfiles_repo="$(dirname $0)"

is_installed(){
	(echo "$@" | tr ' ' '\n' | xargs -L 1 xbps-query)>/dev/null
}

# Take packages to install, and install it any aren't already installed.
install(){
	(echo "$@" | tr ' ' '\n' | xargs -L 1 xbps-query)>/dev/null || sudo xbps-install "$@"
}

stowstar(){
	stow "--dir=${dotfiles_repo}" "$@"
}

# Install GNU Stow
install stow

# Setup dotfiles
mkdir -p ~/.config ~/.config/nvim ~/.config/sway ~/.local/share # Prevent stow from symlinking these root folders
stowstar --dotfiles "--target=$HOME" dotfiles
if [ ! -f ~/.config/nvim/init.vim ]; then
	cp ~/.config/nvim/init.vim.template ~/.config/nvim/init.vim
	echo "Please see ~/.config/nvim/init.vim for information"
fi

# Dependencies of dotfiles
install zsh dunst sxhkd rofi bspwm wmname xrdb xsetroot neovim neovim-remote curl fzf mpd polybar nerd-fonts-otf
# Wayland dependencies
install mako bemenu dmenu hikari sway Waybar xdg-desktop-portal-wlr

# Setup shell
if [ ! "/bin/zsh" = "$(getent passwd $(id -un) | awk -F : '{print $NF}')" ]; then
	chsh -s /bin/zsh
fi

# Setup zinit
zinit_dir="${XDG_DATA_HOME:-$HOME/.local/share}/zinit"

if [ ! -e "$zinit_dir" ]; then
	git clone https://github.com/zdharma-continuum/zinit.git "$zinit_dir"
fi

# Create local bin directory
mkdir -p ~/bin/

# Compile xgetresource
if [ ! -e ~/bin/xgetresource ]; then
	install make gcc libX11-devel
	(cd "$dotfiles_repo/src/getresource" && make && cp xgetresource ~/bin/)
	sudo xbps-remove -R make gcc libX11-devel
fi

sudo stow --no-folding --dir=${dotfiles_repo} --target=/ global

# All hail the desktop stack
## Manually:
## sudo ln -s /etv/sv/seatd /var/service/
## sudo ln -s /etc/sv/rundird /var/service/

if ! is_installed rundird; then
	install rundird
	sudo xbps-pkgdb -m hold rundird
fi
install pipewire wireplumber seatd rundird

if ! id -nG "$USER" | grep -qw "_seatd"; then
	echo "Adding to _seatd"
	sudo usermod -a -G _seatd "$USER"
fi

if ! grep -qw "pam_rundird.so" /etc/pam.d/login; then
	printf "session\toptional\tpam_rundird.so" | sudo tee -a /etc/pam.d/login
fi


git config --replace-all --global include.path "$(realpath "$dotfiles_repo")/gitconfig" "$(realpath "$dotfiles_repo")/gitconfig"
