#######################################################################
#                               macros                                #
#######################################################################

[macros.install__arch]
    deps = ["apacman"]
    prefix = ["apacman", "--noconfirm", "--noedit", "-S"]

[macros.install__void]
    prefix = ["xbps-install", "-S"]

[macros.clone]
    deps = ["git"]
    prefix = ["git", "clone"]

#######################################################################
#                                tasks                                #
#######################################################################

[tasks.apacman]
    rejects = [["which", "apacman"]]
    cmds = [["./bin/install_apacman.sh"]]

[tasks.nvimplug]
  rejects = [["test", "-f", ".config/nvim/autoload/plug.vim"]]
  cmds = [["curl", "-fLo", ".config/nvim/autoload/plug.vim", "--create-dirs", "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"]]

[tasks.nvimpackage]
  rejects = [["which", "nvim"]]
  cmds = [["@install", "neovim-git"]]

[tasks.nvim]
  deps = ["nvimplug", "nvimpackage"]
  links = [[".config/nvim","nvim"]]

[tasks.zshpackage]
  rejects = [["which", "zsh"]]
  cmds = [["@install", "zsh"], ["chsh", "-s", "/usr/bin/zsh"]]

[tasks.zshrc]
  links = [[".zshrc", "dotfiles/.zshrc"]]

[tasks.zsh]
  deps = ["zshrc", "zshpackage"]

[tasks.termite]
  links = [[".config/termite/config", "dotfiles/termite"]]

[tasks.xfiles]
  links = [[".Xresources", "dotfiles/.Xresources"]]

[tasks.i3]
  deps = ["i3"]
  links = [[".config/i3/config", "dotfiles/i3/i3"]]

[tasks.dotfiles]
  links = [[".config/sxhkd/sxhkdrc", "dotfiles/sxhkdrc"],
           [".config/sxhkd/sxhkdrc_bspwm", "dotfiles/sxhkdrc_bspwm"],
           [".config/bspwm", "dotfiles/bspwm"]]

[tasks.curl]
  rejects = [["which", "curl"]]
  cmds = [["@install", "curl"]]

[tasks.hub]
  rejects = [["which", "hub"]]
  deps = ["curl"]
  cmds = [["curl", "-fLo", "/tmp/hub.tgz", "--create-dirs", "https://github.com/github/hub/releases/download/v2.3.0-pre8/hub-linux-amd64-2.3.0-pre8.tgz"],
          ["tar", "xf", "/tmp/hub.tgz", "-C", "${HM_DEST}/bin", "--strip-components=2", "--wildcards", "**/bin/hub"]]

[tasks.git]
  deps = ["hub"]

[tasks.gitbin]
  rejects = [["which", "git"]]
  cmds = [["@install", "git"]]

[tasks.default]
  deps = ["termite",
          "zsh",
          "nvim",
          "xfiles",
          "i3",
          "dotfiles",
          "git"]
