#!/bin/sh

case "$(basename "$(dirname $0)")" in
  light-mode.d) theme="Modus Operandi";;
  dark-mode.d) theme="Modus Vivendi";;
esac

kitty +kitten themes --dump-theme "$theme" > ~/.config/kitty/current-theme.conf
# background the pkill because otherwise darkman gets sad
pkill -x -USR1 kitty &
