#!/bin/sh

case "$(basename "$(dirname $0)")" in
  light-mode.d) mode=0; background=light;;
  dark-mode.d) mode=1; background=dark;;
esac
mode=${1:-$mode}

nvim -e "+let g:DARKMODE=$mode" -e "+set background=$background" +wshada +q

nvr --nostart --serverlist | while read server; do
  # & because https://github.com/mhinz/neovim-remote/issues/105
  nvr -s --servername "$server" -cc rshada -c 'silent call ActivatePreferredColorScheme()' &
done
