#!/bin/sh

cleanup() {
    for tmpfile in $temp_files; do
        [ -f "$tmpfile" ] && rm -f "$tmpfile"
    done
}
trap cleanup EXIT

mktemp_tracked() {
    tmp="$(mktemp "$@")"
    temp_files="$temp_files $tmp"
    echo "$tmp"
}

jb_dir="$(fontdir "jetbrainsmono-2.304")"
if [ ! -d "$jb_dir" ]; then
    output="$(mktemp_tracked --suffix=.tmp)"
    curl --progress-bar -L --output "$output" "https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip"
    oldfiles="$(ls -d "$(fontdir)"/jetbrains* 2>/dev/null)"
    mkdir -p "$jb_dir"
    unzip -d "$jb_dir" "$output" fonts/ttf/JetBrainsMonoNL-Regular.ttf fonts/ttf/JetBrainsMono-Regular.ttf
    [ -n "$oldfiles" ] && rm -rf "$oldfiles"
fi

if [ "linux" = "$ostype" ]; then
    fc-cache -f
fi
