font_family monospace

map ctrl+shift+n new_os_window_with_cwd
map cmd+enter launch --cwd=current
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+y kitten hints --program @
map ctrl+shift+alt+a launch --stdin-source=@last_cmd_output --type=clipboard

allow_remote_control yes

cursor_trail 3

globinclude platform.conf
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

map --new-mode window_nav --on-unknown passthrough --on-action end ctrl+w
map --mode window_nav h neighboring_window left
map --mode window_nav j neighboring_window down
map --mode window_nav k neighboring_window up
map --mode window_nav l neighboring_window right
map --mode window_nav ctrl+w send_text all \x17

map --when-focus-on var:IS_VIM=true ctrl+w>h
map --when-focus-on var:IS_VIM=true ctrl+w>j
map --when-focus-on var:IS_VIM=true ctrl+w>k
map --when-focus-on var:IS_VIM=true ctrl+w>l
map --when-focus-on title:nvim ctrl+w>h
map --when-focus-on title:nvim ctrl+w>j
map --when-focus-on title:nvim ctrl+w>k
map --when-focus-on title:nvim ctrl+w>l
