#!/bin/sh

IFS=$':'
grpcol="$inactive_col"
for i in $1; do
	tagfgcol=""
	tagstr=""
	first=false
	case $i in
		W*)
			i=${i#?}
			first=true
			;;
	esac
	case $i in
		F*)
			tagfgcol="$inactive_col"
			tagstr=" + "
			;;
		f*)
			tagfgcol="$inactive_col"
			tagstr=" - "
			;;
		o*)
			tagfgcol="$active_col"
			tagstr=" - "
			;;
		O*)
			tagfgcol="$active_col"
			tagstr=" + "
			;;
		m*)
			[ $first = false ] && printf " "
			tagfgcol="$inactive_col"
			tagstr="["
			grpcol="$inactive_col"
			;;
		M*)
			# [ $first = false ] && printf " "
			tagfgcol="$sep_col"
			tagstr="["
			grpcol="$sep_col"
			;;
		L*)
			printf "%s" "%{F$grpcol}]"
			;;
		*)
			continue
			;;
	esac
	if [ ! -z $tagstr ] ; then
		printf "%s" "%{F$tagfgcol}"
		# clickable tags
		printf "%s" $tagstr #${i:1} to get the text
	fi
done
printf "%s\n" "%{F-}"
