#!/bin/sh

NUM_MON=$(bspc query -M | wc -l)

bright_yellow="$(xgetresource panel.color11)"
bright_red="$(xgetresource panel.color1)"
bright_green="$(xgetresource panel.color10)"
bright_orange="$(xgetresource panel.orange)"
neutral_aqua="$(xgetresource panel.color14)"

while read -r line; do
	old_output="$output"
	case $line in
		D*)
			clock="${line#?}"
			;;
		T*)
			title="${line#?}"
			;;
		W*)
			workspaces="$(active_col="$bright_yellow" inactive_col="$light4" sep_col="$bright_red" $SCRIPT_DIR/bspwm_format "$line")"
			;;
		BS*)
			case ${line#??} in
				Full)
					battery_status="%{F$bright_green}"
					;;
				Charging)
					battery_status="%{F$bright_yellow}"
					;;
				Discharging)
					battery_status="%{F$bright_red}"
					;;
				*)
					battery_status="%{F$bright_red}${line#??}"
					;;
			esac
			;;
		BC*)
			battery_capacity="${line#??}%{F-}"
			;;
		X*)
			wifi_name="${line#?}"
			if [ -z "$wifi_name" ]; then
				wifi="%{F$bright_red} Disconnected%{F-}"
			else
				wifi="%{F$bright_green} ${line#?}%{F-}";
			fi
			;;
		VM*)
			volumeicon="%{F$neutral_aqua}"
			case ${line#??} in
				on)
					volumeicon="$volumeicon"
					;;
				off)
					volumeicon="$volumeicon"
					;;
			esac
			volumeicon="$volumeicon%{F-}"
			;;
		VL*)
			volume="%{F$neutral_aqua}${line#??}%{F-}"
			;;
		Refresh)
			old_output=""
			;;
	esac

	output="%{c}$title%{l}$workspaces%{r}$volumeicon $volume $wifi $battery_status $battery_capacity $clock"
	barout=""
	for m in $NUM_MON; do
		barout=$barout$output
	done
	if [ "$old_output" != "$output" ]; then
		printf "%s\n" "$barout"
	fi;
done
